dist: trusty
sudo: false

language: python
python:
  - "3.6"

env:
 - ZSH_TARGET="5.4.2"
 - ZSH_TARGET="5.3.1"
 - ZSH_TARGET="5.2"
 - ZSH_TARGET="5.1.1"

before_install:
    # setup ccache to run instead of gcc
    - export PATH="/usr/lib/ccache:$PATH"
    # Download zsh
    - export LOCAL="$(mktemp --directory --tmpdir=${TMPDIR:/tmp} local.bin.XXXXXX)"
    - wget "https://downloads.sourceforge.net/project/zsh/zsh/$ZSH_TARGET/zsh-$ZSH_TARGET.tar.xz"

install:
    - pip install restructuredtext_lint
    # Build and install zsh
    - tar -xf zsh-$ZSH_TARGET.tar.xz
    - cd zsh-$ZSH_TARGET
    - ./configure --prefix=$LOCAL
    - make
    - make install
    - cd -
    - export PATH="$LOCAL/bin:$PATH"

before_script:
    - mkdir -p ~/bin
    - curl -L https://raw.githubusercontent.com/molovo/revolver/master/revolver > ~/bin/revolver
    - curl -L https://github.com/molovo/zunit/releases/download/v0.8.2/zunit > ~/bin/zunit
    - chmod u+x ~/bin/{revolver,zunit}

script:
    - rst-lint *.rst
    - zunit --verbose


cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.ccache"
