dnl BKG_PACKAGE_INFO(PACKAGE_SUMMARY)
dnl ---------------------------------
dnl
dnl Substitutions BKG_PACKAGE_NAME, BKG_PACKAGE_SUMMARY & BKG_PACKAGE_VERSION
dnl
AC_DEFUN([BKG_PACKAGE_INFO],
[
    AC_SUBST(BKG_PACKAGE_NAME, AC_PACKAGE_NAME)
    AC_SUBST(BKG_PACKAGE_SUMMARY, $1)
    AC_SUBST(BKG_PACKAGE_VERSION, AC_PACKAGE_VERSION)
])dnl
